#!/bin/bash
sdoc_to_markdown() {
  sdoc cat markdown::$1.sdoc > $1.md
}

sdoc_to_code() {
  sdoc cat code::$1.sdoc > $1
}

bake %x.md : %x.sdoc :: sdoc_to_markdown %x
bake %x    : %x.sdoc :: sdoc_to_code %x

create_bake() {
  cat bake.sh bake-template > bake
  chmod +x bake
}

bake %@sdocs.sdoc = *.sdoc

bake bake : bake.sh bake-template :: create_bake
bake : bake bake.sh %@sdocs.md
