#!/bin/bash
# Bake: bash build tool | Spencer Tipping
# Licensed under the terms of the MIT source code license

__bake_sh_goes_here__

bake-instance bake    # this is visible to the bakefile

# Load the bakefile from the appropriate ancestor directory
if bake --find-bakefile; then
  cd "$( bake --base-dir )"
  source [Bb]akefile
  bake --run "$@"
fi
